server:
  port: 8763

spring:
  application:
    name: config-server

  profiles:
    active: native


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    default-zone: http://localhost:8761
